//
//  MusicStyle.swift
//  musicity
//
//  Created by Brian Friess on 25/11/2021.
//

import Foundation

let musicStyle = ["Afropop",
                  "AfroTrap",
                  "Blues",
                  "Ballet",
                  "Beatbox",
                  "Big band",
                  "Britpop",
                  "Chill",
                  "Classique",
                  "Country",
                  "Disco",
                  "Dance",
                  "Death metal",
                  "Deep house",
                  "Djent",
                  "Dub",
                  "Dubstep",
                  "Drill",
                  "Electro",
                  "ElectroSwing",
                  "Emo",
                  "Eurobeat",
                  "Folk",
                  "Free jazz",
                  "French touch",
                  "Fenchcore",
                  "Funk",
                  "Garage rock",
                  "Glam rock",
                  "Gospel",
                  "Grunge",
                  "Hard rock",
                  "Hard trance",
                  "Hardstyle",
                  "Heavy metal",
                  "Hip-hop",
                  "House",
                  "indie pop",
                  "Indies",
                  "J-pop",
                  "Jazz",
                  "K-pop",
                  "Math rock",
                  "Metal alternatif",
                  "Metal industriel",
                  "Metalcore",
                  "Musette",
                  "Musique Acoustique",
                  "Musique baroque",
                  "Musique bretonne",
                  "Musique celtique",
                  "Metal progressif",
                  "Metal",
                  "New wave",
                  "NintedoCore",
                  "Nu metal",
                  "Opera",
                  "Opera rock",
                  "Post rock",
                  "Power pop",
                  "Power metal",
                  "Pop",
                  "Punk",
                  "Psychedelique",
                  "Punk rock",
                  "Reaggaeton",
                  "Rock",
                  "Rock alternatif",
                  "Rockabilly",
                  "Rumba",
                  "Rap",
                  "Reggae",
                  "Rock 'n' Roll",
                  "R'n'B",
                  "Samba",
                  "Stoner",
                  "Synthpop",
                  "Synthwave",
                  "Salsa",
                  "Ska",
                  "Soul",
                  "Swing",
                  "Tango",
                  "Tech house",
                  "Techno",
                  "Trance",
                  "Trap",
                  "variété",
                  "Zouk",
                  "Zumba"
]
