//
//  MusicInstruments.swift
//  musicity
//
//  Created by Brian Friess on 27/11/2021.
//

import Foundation

let musicInstruments = ["accordéon",
                        "alto",
                        "banjo",
                        "baryton",
                        "basse",
                        "basson",
                        "batterie",
                        "bongo",
                        "cajon",
                        "carillon",
                        "celesta",
                        "chant",
                        "cithare",
                        "clairon",
                        "clarinette",
                        "claves",
                        "congas",
                        "contrebasse",
                        "cor",
                        "cornamuse",
                        "corne",
                        "djembe",
                        "flute",
                        "flute a coulisse",
                        "flute de pan",
                        "flute nasal",
                        "guimbarde",
                        "guitare acoustique",
                        "guitare electrique",
                        "harmonica",
                        "harpe",
                        "hautbois",
                        "kazoo",
                        "luth",
                        "lyre",
                        "mandoline",
                        "musique assistée par ordinateur",
                        "mellotron",
                        "melodica",
                        "ocarina",
                        "orgue",
                        "piano",
                        "piano electrique",
                        "piccolo",
                        "pipeau",
                        "saxophone",
                        "synthetiseur",
                        "tam tam",
                        "tambour",
                        "tambourin",
                        "timbales",
                        "trombone",
                        "trompette",
                        "tuba",
                        "ukulele",
                        "vibraphone",
                        "violon",
                        "violoncelle",
                        "vuvuzela",
                        "xylophone"
]
